-- vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
--
-- transparent background
vim.cmd("highlight Normal guibg=none")
vim.cmd("highlight NormalFloat guibg=none")
vim.cmd("highlight FloatBorder guibg=none")
vim.cmd("highlight FloatTitle guibg=none")
vim.cmd("highlight TabLineFill guibg=none")
vim.cmd("highlight Pmenu guibg=none")
vim.cmd("highlight Terminal guibg=none")
vim.cmd("highlight EndOfBuffer guibg=none")
vim.cmd("highlight FoldColumn guibg=none")
vim.cmd("highlight Folded guibg=none")
vim.cmd("highlight SignColumn guibg=none")
vim.cmd("highlight NormalNC guibg=none")
vim.cmd("highlight TelescopeBorder guibg=none")
vim.cmd("highlight TelescopeNormal guibg=none")
vim.cmd("highlight TelescopePromptBorder guibg=none")
vim.cmd("highlight TelescopePromptTitle guibg=none")
vim.cmd("highlight LineNr guibg=none")
vim.cmd("highlight ErrorMsg guibg=none")

vim.cmd("highlight @markup.raw.markdown_inline guibg=none")
vim.cmd("highlight @markup.heading.1.markdown guibg=none")

-- transparent background for neotree
vim.cmd("highlight NeoTreeNormal guibg=none")
vim.cmd("highlight NeoTreeNormalNC guibg=none")
vim.cmd("highlight NeoTreeVertSplit guibg=none")
vim.cmd("highlight NeoTreeWinSeparator guibg=none")
vim.cmd("highlight NeoTreeEndOfBuffer guibg=none")

-- transparent background for nvim-tree
vim.cmd("highlight NvimTreeNormal guibg=none")
vim.cmd("highlight NvimTreeVertSplit guibg=none")
vim.cmd("highlight NvimTreeEndOfBuffer guibg=none")

-- transparent notify background
vim.cmd("highlight NotifyINFOBody guibg=none")
vim.cmd("highlight NotifyERRORBody guibg=none")
vim.cmd("highlight NotifyWARNBody guibg=none")
vim.cmd("highlight NotifyTRACEBody guibg=none")
vim.cmd("highlight NotifyDEBUGBody guibg=none")
vim.cmd("highlight NotifyINFOTitle guibg=none")
vim.cmd("highlight NotifyERRORTitle guibg=none")
vim.cmd("highlight NotifyWARNTitle guibg=none")
vim.cmd("highlight NotifyTRACETitle guibg=none")
vim.cmd("highlight NotifyDEBUGTitle guibg=none")
vim.cmd("highlight NotifyINFOBorder guibg=none")
vim.cmd("highlight NotifyERRORBorder guibg=none")
vim.cmd("highlight NotifyWARNBorder guibg=none")
vim.cmd("highlight NotifyTRACEBorder guibg=none")
vim.cmd("highlight NotifyDEBUGBorder guibg=none")

-- -- BufferLine
vim.cmd("highlight BufferLineBackground guibg=none")
vim.cmd("highlight BufferLineBuffer guibg=none")
vim.cmd("highlight BufferLineBufferSelected guibg=none")
vim.cmd("highlight BufferLineBufferVisible guibg=none")
vim.cmd("highlight BufferLineCloseButton guibg=none")
vim.cmd("highlight BufferLineCloseButtonSelected guibg=none")
vim.cmd("highlight BufferLineCloseButtonVisible guibg=none")
vim.cmd("highlight BufferLineDuplicate guibg=none")
vim.cmd("highlight BufferLineDuplicateSelected guibg=none")
vim.cmd("highlight BufferLineDuplicateVisible guibg=none")
vim.cmd("highlight BufferLineError guibg=none")
vim.cmd("highlight BufferLineErrorDiagnostic guibg=none")
vim.cmd("highlight BufferLineErrorDiagnosticSelected guibg=none")
vim.cmd("highlight BufferLineErrorDiagnosticVisible guibg=none")
vim.cmd("highlight BufferLineErrorSelected guibg=none")
vim.cmd("highlight BufferLineErrorVisible guibg=none")
vim.cmd("highlight BufferLineFill guibg=none")
vim.cmd("highlight BufferLineIndicator guibg=none")
vim.cmd("highlight BufferLineIndicatorSelected guibg=none")
vim.cmd("highlight BufferLineIndicatorVisible guibg=none")
vim.cmd("highlight BufferLineInfo guibg=none")
vim.cmd("highlight BufferLineInfoDiagnostic guibg=none")
vim.cmd("highlight BufferLineInfoDiagnosticSelected guibg=none")
vim.cmd("highlight BufferLineInfoDiagnosticVisible guibg=none")
vim.cmd("highlight BufferLineInfoSelected guibg=none")
vim.cmd("highlight BufferLineInfoVisible guibg=none")
vim.cmd("highlight BufferLineMiniIconsAzure guibg=none")
vim.cmd("highlight BufferLineMiniIconsAzureInactive guibg=none")
vim.cmd("highlight BufferLineMiniIconsAzureSelected guibg=none")
vim.cmd("highlight BufferLineMiniIconsGrey guibg=none")
vim.cmd("highlight BufferLineMiniIconsGreyInactive guibg=none")
vim.cmd("highlight BufferLineMiniIconsGreySelected guibg=none")
vim.cmd("highlight BufferLineModified guibg=none")
vim.cmd("highlight BufferLineModifiedSelected guibg=none")
vim.cmd("highlight BufferLineModifiedVisible guibg=none")
vim.cmd("highlight BufferLinePick guibg=none")
vim.cmd("highlight BufferLinePickSelected guibg=none")
vim.cmd("highlight BufferLinePickVisible guibg=none")
vim.cmd("highlight BufferLineSeparator guibg=none")
vim.cmd("highlight BufferLineSeparatorSelected guibg=none")
vim.cmd("highlight BufferLineSeparatorVisible guibg=none")
vim.cmd("highlight BufferLineTab  guibg=none")
vim.cmd("highlight BufferLineTabClose guibg=none")
vim.cmd("highlight BufferLineTabSelected guibg=none")
vim.cmd("highlight BufferLineTabSeparator guibg=none")
vim.cmd("highlight BufferLineTabSeparatorSelected guibg=none")
vim.cmd("highlight BufferLineWarning guibg=none")
vim.cmd("highlight BufferLineWarningDiagnostic guibg=none")
vim.cmd("highlight BufferLineWarningDiagnosticSelected guibg=none")
vim.cmd("highlight BufferLineWarningDiagnosticVisible guibg=none")
vim.cmd("highlight BufferLineWarningSelected guibg=none")
vim.cmd("highlight BufferLineWarningVisible guibg=none")

-- Whichkey
vim.cmd("highlight WhichKeyFloat guibg=none")
vim.cmd("highlight WhichKeyNormal guibg=none")
vim.cmd("highlight WhichKeyBorder guibg=none")

-- Snacks
vim.cmd("highlight SnacksNotifier guibg=none")
vim.cmd("highlight SnacksNotifierBorderInfo guibg=none")
vim.cmd("highlight SnacksNotifierError guibg=none")
vim.cmd("highlight SnacksNotifierBorderError guibg=none")
vim.cmd("highlight SnacksNotifierBorderDebug guibg=none")
vim.cmd("highlight SnacksNotifierTrace guibg=none")
vim.cmd("highlight SnacksNotifierInfo guibg=none")
vim.cmd("highlight SnacksNotifierWarn guibg=none")
vim.cmd("highlight SnacksNotifierDebug guibg=none")
vim.cmd("highlight SnacksNotifierBorderTrace guibg=none")
vim.cmd("highlight SnacksNotifierBorderWarn guibg=none")
vim.cmd("highlight SnacksNotifierBorderWarn guibg=none")

vim.cmd("highlight SnacksPicker guibg=none")
vim.cmd("highlight SnacksPickerPickWinCurrent guibg=none")
vim.cmd("highlight SnacksPickerBorder guibg=none")
vim.cmd("highlight SnacksPickerPreview guibg=none")
vim.cmd("highlight SnacksPickerPreviewBorder guibg=none")
vim.cmd("highlight SnacksPickerList guibg=none")
vim.cmd("highlight SnacksPickerListBorder guibg=none")
vim.cmd("highlight SnacksPickerInput guibg=none")
vim.cmd("highlight SnacksPickerInputBorder guibg=none")
vim.cmd("highlight SnacksPickerTitle guibg=none")
vim.cmd("highlight SnacksPickerTitleBorder guibg=none")
vim.cmd("highlight SnacksPickerToggle guibg=none")

vim.cmd("highlight SnacksTerminal guibg=none")
vim.cmd("highlight SnacksTerminalBorder guibg=none")
vim.cmd("highlight SnacksTerminalTitle guibg=none")

vim.cmd("highlight SnacksInput guibg=none")
vim.cmd("highlight SnacksInputBorder guibg=none")
vim.cmd("highlight SnacksInputTitle guibg=none")

vim.cmd("highlight SnacksDashboard guibg=none")
vim.cmd("highlight SnacksDashboardNormal guibg=none")
vim.cmd("highlight SnacksPickerCursor guibg=none")
vim.cmd("highlight SnacksPickerCursorLine guibg=none")
vim.cmd("highlight SnacksPickerPreviewTitle guibg=none")
vim.cmd("highlight SnacksPickerListTitle guibg=none")
vim.cmd("highlight SnacksPickerInputSearch guibg=none")
vim.cmd("highlight SnacksPickerBoxBorder guibg=none")
vim.cmd("highlight SnacksNotifierBorder guibg=none")
vim.cmd("highlight SnacksExplorer guibg=none")
vim.cmd("highlight SnacksExplorerBorder guibg=none")
vim.cmd("highlight SnacksExplorerTitle guibg=none")
vim.cmd("highlight SnacksScrollThumb guibg=none")
vim.cmd("highlight SnacksZen      guibg=none")
vim.cmd("highlight SnacksWords    guibg=none")
vim.cmd("highlight SnacksScratch  guibg=none")
vim.cmd("highlight SnacksScratchBorder guibg=none")
vim.cmd("highlight SnacksScratchTitle guibg=none")
vim.cmd("highlight SnacksStatusColumn guibg=none")

vim.cmd("highlight SnacksWinBarNC guibg=none")
vim.cmd("highlight SnacksNormalNC guibg=none")
vim.cmd("highlight SnacksBackdrop guibg=none")
vim.cmd("highlight SnacksWinBar   guibg=none")
vim.cmd("highlight SnacksNormal   guibg=none")

-- Noice
vim.cmd("highlight NoiceCmdline   guibg=none")
vim.cmd("highlight NoiceCmdlinePopup guibg=none")
vim.cmd("highlight NoiceCmdlinePopupBorder guibg=none")
vim.cmd("highlight NoiceConfirm   guibg=none")
vim.cmd("highlight NoiceConfirmBorder guibg=none")
vim.cmd("highlight NoicePopup     guibg=none")
vim.cmd("highlight NoicePopupBorder guibg=none")
vim.cmd("highlight NoicePopupmenu guibg=none")
vim.cmd("highlight NoicePopupmenuBorder guibg=none")
vim.cmd("highlight NoicePopupmenuSelected guibg=none")
vim.cmd("highlight NoiceSplit     guibg=none")
vim.cmd("highlight NoiceSplitBorder guibg=none")
vim.cmd("highlight NoiceMini      guibg=none")
vim.cmd("highlight NoiceScrollbar guibg=none")
vim.cmd("highlight NoiceScrollbarThumb guibg=none")
vim.cmd("highlight NoiceCursor    guibg=none")
vim.cmd("highlight NoiceHistory   guibg=none")
vim.cmd("highlight NoiceHistoryBorder guibg=none")

-- Mini
vim.cmd("highlight MiniNotifyNormal guibg=none")
vim.cmd("highlight MiniNotifyBorder guibg=none")

-- Trouble
vim.cmd("highlight TroubleCount guibg=none")
vim.cmd("highlight TroubleNormal guibg=none")

-- Treesitter Context
vim.cmd("highlight TreesitterContextLineNumber guibg=none")

-- Git SignColumn
vim.cmd("highlight GitSignsAdd guibg=none")
vim.cmd("highlight GitSignsChange guibg=none")
vim.cmd("highlight GitSignsDelete guibg=none")
